// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzhxrzacotesaryhpzou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6aHhyemFjb3Rlc2FyeWhwem91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NzExNDcsImV4cCI6MjA1OTE0NzE0N30.gyqlwE0-bJQvnbqmP7_TsMTwDiIO1NCYpAJK_6W4fs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);